### ISSUE TITLE
Complete the renaming

### ISSUE THREAD

**Issue by braney** [ESMG/PyCNAL#1]
Rename "pyroms" to "PyCNAL" everywhere within filenames, code, and documentation.

**Comment by kshedstrom** [comment]
Anyone know how to regenerate the docs files?

**Comment by braney** [comment]
Not me, but the doc files mention "epydoc", which is a project here:

    http://epydoc.sourceforge.net/

I don't see it installed on Enrique's machines though.

I'm familiar with the "Doxygen" tool, which is similar, but may require
altering the inline documentation (if any) to use it.

On Thu, Jul 14, 2016 at 3:12 PM, Kate Hedstrom <notifications@github.com>
wrote:

> Anyone know how to regenerate the docs files?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESMG/PyCNAL/issues/1#issuecomment-232763543>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQwqUxvQhLM2gVyroBhse_jEf57-3DI-ks5qVoovgaJpZM4H9GPU>
> .
>



-- 
Bryan Raney
Laboratory Researcher
Center for Environmental Prediction
Rutgers University

**Comment by kshedstrom** [comment]
Thanks for tracking that down - seems like a dormant project (2008,
python2.5). I vote for switching to doxygen!

Kate

**Comment by kshedstrom** [comment]
Doxygen it is - will update the .doxygen files later (used an old version of doxygen).
