### ISSUE TITLE
jday2date in the toolbox is now wrong

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/PyCNAL#12]
The thing counts on the python 2 behavior for integer division. I threw in some int() around things and it still fails with:

 File "/u1/uaf/kshedstrom/python/lib/python3.5/site-packages/pycnal_toolbox/jday2date.py", line 46, in jday2date
    date.append(datetime(Y,M,D,h,m,s))
ValueError: day is out of range for month

Looking at the output, it never goes to day 31 of the relevant months. It died on June 30.

**Comment by braney** [comment]
You can replace "a / b" with "a // b" to get the Python 2 behavior.

**Comment by kshedstrom** [comment]
Thanks, that works!
