### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by braney** [ESMG/PyCNAL#3]

**Comment by kshedstrom** [comment]
I pushed a start to the py3 branch. Needs more testing.

**Comment by kshedstrom** [comment]
Using the "2to3 -w" command worked for all but a few files:
1. pyroms_toolbox/pyroms_toolbox/seawater/test.py had some non-Unicode instances of a degree symbol (tiny circle). I deleted them, but they could be reintroduced if desired.
2. pyroms/pyroms/tools.py had a variable "long" get converted to "int" which led to a runtime error.
3. Could be others....
